production:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  doge_api_key: <%= ENV["DOGE_API_KEY"] %>
  bucket: <%= ENV["S3_BUCKET_NAME"] %>
